make Principal Serializeable for quartz clustering.
If we didn't do this, we'd end up getting a quartz exception when
it tried to serialize the job to the database for clustering.

Caused by: org.quartz.JobPersistenceException: Couldn't store job: Unable to
serialize JobDataMap for insertion into database because the value of property
'principal_key' is not serializable:
org.fedoraproject.candlepin.auth.UserPrincipal [See nested exception:
java.io.NotSerializableException: Unable to serialize JobDataMap for insertion
into database because the value of property 'principal_key' is not serializable:
org.fedoraproject.candlepin.auth.UserPrincipal]