Remove non-ASCII character that breaks tito rpm build
- This fixes the following error thrown by the Cheetah template
  engine used by tito, when building the rpm:

  File "/usr/lib64/python2.7/site-packages/Cheetah/Compiler.py", line 1711, in __init__
    source = unicode(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 8104: ordinal not in range(128)